language: node_js
node_js:
  - node
  - 10
notifications:
  email: false
sudo: false
script:
  - npm run test
  - npm run lint
  - npm run build
after_success:
  - rm -fr ./dist
  - npm run build
  - semantic-release
